// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RestClientVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "RestClientVS.a7b4a362-3ce8-4953-9b19-a35166f2cbfd";
        public const string Name = "Rest Client";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0.3";
        public const string Author = "Mads Kristensen";
        public const string Tags = "rest, http, postman";
    }
}
