// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RestClientVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "RestClientVS.a7b4a362-3ce8-4953-9b19-a35166f2cbfd";
        public const string Name = "REST Client";
        public const string Description = @"REST Client allows you to send HTTP request and view the response in Visual Studio directly. Based on the popular VS Code extension";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Mads Kristensen";
        public const string Tags = "rest, http, postman";
    }
}
