// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RestClientVS
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string RestEditorFactoryString = "ed091b30-0d58-4343-9c24-4aad5c417422";
        public static Guid RestEditorFactory = new Guid(RestEditorFactoryString);

        public const string RestClientVSString = "bb294b08-c71b-4feb-8772-5a10f5b8b36c";
        public static Guid RestClientVS = new Guid(RestClientVSString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RestCodeWin = 0x0001;
        public const int SendRequest = 0x0100;
    }
}